### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by MarkWithall** [doersino/snooker-commentary-generator#1]
Nice app!  Just noticed a spelling error on the first line of commentary that came up.

[app.js line 96](https://github.com/doersino/snooker-commentary-generator/blob/master/app.js#L96):

> "I think he can get through to this read near the middle pocket, it's definitely cuttable."

Should be 'red' rather than 'read'.

**Comment by doersino** [comment]
Thank you! Fixed.

**Comment by MarkWithall** [comment]
That may have been a new world record for world's fastest bugfix :)  Well done.
